### ISSUE TITLE
Replace Jeff's murder map data with new data

### ISSUE THREAD

**Issue by akanik** [publicsource/gunmap#1]
http://publicsource.org/investigations/map-pittsburghs-solved-and-unsolved-murders#.V-vLDpMrKV4

We can use this map as a boilerplate to build off of.

**Comment by khantasha** [comment]
For some reason it's not letting me commit and push Jeff's murder map files to the cloud. Maybe I'm doing something wrong...will try again tomorrow. If not, we can just pull it in tomorrow. I have Jeff's finalized data, too. So I'm guessing there's probably some way to convert csv data to geojson? I'll google. :)

**Comment by akanik** [comment]
CSVKit is going to be your best friend: http://csvkit.readthedocs.io/en/0.9.1/

Is there already lat/long data in the csv?

If yes, your code is going to be something like: 
`csvjson --lat latitude --lon longitude --k slug --crs EPSG:4269 -i 4 examples/test_geo.csv`

We can talk about this tomorrow.

**Comment by khantasha** [comment]
There is no lat/long in data. But we have addresses, so I guess I'll have to find those first.

**Comment by khantasha** [comment]
So I will handcode whatever's left after you convert the tsv to geojson. What are you using? Aldhous's thing again? Is it working on yours?
